<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\Categoria\**" />
    <Content Remove="Pages\Categoria\**" />
    <EmbeddedResource Remove="Pages\Categoria\**" />
    <None Remove="Pages\Categoria\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Pages\Categoria.razor" />
    <Content Remove="Pages\MovimientoInventario.razor" />
    <Content Remove="Pages\Producto.razor" />
    <Content Remove="Pages\Usuario.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.31" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.31" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.31" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SysGestionVentas.ApiClient\SysGestionVentas.ApiClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Authentication\Logout.razor" />
    <None Include="Pages\Categorias\Categoria.razor" />
    <None Include="Pages\MovimientoInventario\MovimientoInventario.razor" />
    <None Include="Pages\Productos\Producto.razor" />
    <None Include="Pages\Admin\Usuario.razor" />
  </ItemGroup>

</Project>